apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
  labels:
    app: jenkins-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
      - name: jenkins-k8s-demo
        image: YOUR_DOCKERHUB_USERNAME/jenkins-k8s-demo:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5