apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-demo
  labels:
    app: jenkins-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: jenkins-k8s-demo
    spec:
      containers:
      - name: jenkins-k8s-demo
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5